# vim: set sw=4 et:

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

if [ "$(uname -s)" = Darwin ]; then
    OS=macos
else
    OS=$(grep "^ID=" /etc/os-release | cut -d '=' -f 2)
fi

HISTSIZE=999999999
SAVEHIST=$HISTSIZE

source ~/.antidote/antidote.zsh

export YSU_MESSAGE_POSITION="after" # you-should-use message
export NVM_LAZY_LOAD=true
antidote load ~/dotfiles/zsh/plugins.txt

[[ -a ~/.zsh_private ]] && source ~/.zsh_private # secrets that can't go on github should go in this file
[[ -a ~/dotfiles/zsh/$OS.zsh ]] && source ~/dotfiles/zsh/$OS.zsh # OS-specific config should go in e.g. macos.zsh or arch.zsh

~/.fly/bin/fly completion zsh 2> /dev/null >| "$ZSH_CACHE_DIR/completions/_fly" &|
~/.fly/bin/flyctl completion zsh 2> /dev/null >| "$ZSH_CACHE_DIR/completions/_flyctl" &|

eval "$(zoxide init --cmd j zsh)"

eval "$(atuin init zsh --disable-up-arrow)"

source ~/dotfiles/zsh/aliases.zsh

export EDITOR='nvim'

path=(
    ~/.cargo/bin
    ~/.local/bin
    ~/.fly/bin
    ~/go/bin
    ~/.gem/ruby/2.6.0/bin
    /usr/local/sbin
    $path
)
export PATH

export LESS=-RXF

export RIPGREP_CONFIG_PATH=~/dotfiles/ripgreprc

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

eval "$(direnv hook zsh)"

[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(codium --locate-shell-integration-path zsh)" || true
